name: Ruff Formatting

on:
  workflow_call:
    inputs:
      context:
        required: false
        type: string
        default: 'ruff-format'
        description: 'Identifier for the workflow when reporting status'
      continue-on-error:
        required: false
        type: boolean
        default: false
        description: 'When set to true, the workflow will continue even if there are errors'
      uv-sync-args:
        required: false
        type: string
        default: '--extra dev'
        description: 'Argument string to pass to `uv sync --locked` when setting up the environment. E.g. passing --dev results in `uv sync --locked --dev'

permissions:
  statuses: write
  contents: read

jobs:
  ruff-format:
    name: Ruff Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: Install uv and gh dependencies
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        uv sync --locked ${{ inputs.uv-sync-args }}
        gh extension install thetechcollective/gh-set-status --pin stable

    - name: Check with ruff
      id: formatting
      continue-on-error: ${{ inputs.continue-on-error }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Dont exit if the next command fails, we want to capture the exit code
        set +e
        uv run ruff format --check .
        result=$?
        set -e
        if [ $result -eq 0 ]; then
          gh set-status success "All formatting checks passed" "${{ inputs.context }}"
        else
          gh set-status failure "Some formatting checks failed" "${{ inputs.context }}"
        fi
        exit $result
