name: Pytest

on:
  workflow_call:
    inputs:
      context:
        required: false
        type: string
        default: 'unittest'
        description: 'Identifier for the workflow when reporting status'
      arguments:
        required: false
        type: string
        default: ''
        description: 'The argument string to pass to pytest (default is none)'
      uv-sync-args:
        required: false
        type: string
        default: '--extra dev'
        description: 'Argument string to pass to `uv sync --locked` when setting up the environment. E.g. passing --dev results in `uv sync --locked --dev'
      


permissions:
  statuses: write
  contents: read

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: Install uv and gh dependencies
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        uv sync --locked ${{ inputs.uv-sync-args }}
        gh extension install thetechcollective/gh-set-status --pin stable

    - name: Test with pytest
      id: unittest
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . .venv/bin/activate
        # Dont exit if the next command fails, we want to capture the exit code
        set +e
        pytest ${{ inputs.arguments }}
        result=$?
        set -e
        if [ $result -eq 0 ]; then
          gh set-status success "All tests passed and threshold on line coverage reached" "${{ inputs.context }}"
        else
          gh set-status failure "Some tests failed or threshold on line covearage not reached" "${{ inputs.context }}"
        fi
        exit $result
